import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MenShoppingCartProvider  from '@/context/MenShoppingCartContext'
//
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
   
      <body className={`${inter.className} w-full h-full bg-black flex flex-col m-0 p-0 `} suppressHydrationWarning={true}>
          <MenShoppingCartProvider>
          <Header />
          {children}
          </MenShoppingCartProvider>
      </body>
    </html>
  )
}
